# This is a basic workflow to help you get started with Actions

name: build-book

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  build:
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Cache bookdown results
        uses: actions/cache@v1
        with:
          path: _bookdown_files
          key: bookdown-2-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-2-

      - name: Install pandas
        run: Rscript -e "library(reticulate); py_install('pandas')"

      - name: Render book
        run: Rscript -e 'bookdown::render_book("index.Rmd", quiet = TRUE)'

      - name: Upload book folder for debug
        uses: actions/upload-artifact@v2
        with:
          name: book-dir
          path: public

  checkout-and-deploy:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          # Artifact name
          name: book-dir # optional
          # Destination path
          path: public # optional
      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@v3
        with:
         build_dir: public
         branch: gh-pages